import Navbar from "@/sections/navbar";
import ServiceDetailsCard from "@/components/service_details_card";
import SliderComp from "@/sections/slider";
import HeaderBar from "@/sections/header_bar";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import About from "@/sections/about";
import ServiceCard from "@/components/service_card";
import ServicesDetails from "@/sections/services_details";
import ServiceDetailsSlider from "@/components/service_details_slider";
import MultipleItems from "@/sections/check";
import SlickSlider from "@/sections/check";
import initializeAOS from "../utils/aos";
import Footer from "@/sections/footer";
import { useEffect } from "react";
import Plans from "@/sections/plans";
import ProjectsGallery from "@/sections/projects_gallery";
import Image from "next/image";

export default function Home() {
  useEffect(() => {
    initializeAOS();
  }, []);
  const handleButtonClick = () => {
    window.open("https://api.whatsapp.com/send?phone=03326556262", "_blank");
  };
  return (
    <>
      <Head>
        <title>Fizz Innovations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-aos="fade-up">
        <HeaderBar />
        <Navbar />
        <SliderComp />
        <About />
        {/* <h1 data-aos="fade-up">Animated Heading</h1>
        <p data-aos="zoom-in" data-aos-delay="100">
          Animated Paragraph
        </p> */}
        <ServicesDetails />
        {/* <Plans /> */}
        <ProjectsGallery />
        <Footer />
        <button
          onClick={handleButtonClick}
          className="
        fixed
        right-4
        bottom-4
        z-[9999]
        "
        >
          {/* <div
          className="bg-gray-400
          p-4
          rounded-xl
          "
          >
            <p>for any queries</p>
          </div> */}
          <Image
            src={require("../assets/icons/whatsapp_icon.png")}
            alt="whatsapp"
            className="w-12  z-[-1] animate-bounce"
          />
        </button>
      </main>
    </>
  );
}
